In [1]:
# print normal array
import numpy as np
myarr = np.array([3,6,32,7])
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7])

In [2]:
# print with data type
myarr = np.array([3,6,32,7],np.int8)
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7], dtype=int8)

In [3]:
myarr = np.array([3,6,32,7],np.int8)
print([0,1])
print(myarr[0])
myarr

[0, 1]
3


array([ 3,  6, 32,  7], dtype=int8)

In [4]:
myarr = np.array([[3,6,32,7]],np.int8)
print(myarr[0])
print(myarr[0,1])
myarr

[ 3  6 32  7]
6


array([[ 3,  6, 32,  7]], dtype=int8)

In [5]:
# change the element
myarr = np.array([[3,6,32,7]],np.int8)
myarr[0,1] = 45
print(myarr)
myarr

[[ 3 45 32  7]]


array([[ 3, 45, 32,  7]], dtype=int8)

*array creations: Conversion from other Python structure*

In [6]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)
listarray

[[1 2 3]
 [5 8 5]
 [0 3 1]]


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [7]:
# check data type
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.dtype

dtype('int32')

In [8]:
# check shape of the array
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.shape

(3, 3)

In [9]:
# check the array element array size
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.size

9

In [10]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [11]:
zeros = np.zeros((2,5))
zeros.dtype

dtype('float64')

In [12]:
zeros = np.zeros((2,5))
zeros.shape 

(2, 5)

In [13]:
zerso = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# it is print untill the range function
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# it is give the value of two different parameter
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [16]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
lspace = np.linspace(1,4,4)
lspace

array([1., 2., 3., 4.])

In [18]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [19]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [20]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
ide = np.identity(45)
ide.shape

(45, 45)

In [23]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
# for multidimentional array
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [25]:
# for 1D array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr.shape

(99,)

_numpy axis_

In [27]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [28]:
# all sum to x axis
x = [[1,2,3],[4,5,6],[7,1,0]]
ar.sum(axis=0)

array([12,  8,  9])

In [29]:
# all sum to y axis
x = [[1,2,3],[4,5,6],[7,1,0]]
ar.sum(axis=1)

array([ 6, 15,  8])

In [30]:
# transpose matrix
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [31]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.flat

In [32]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [33]:
# check number dimention
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.ndim

2

In [34]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
arr.size

99

In [35]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.nbytes

36

In [36]:
# find max argmunent index
one = np.array([1,3,4,634,2])
one.argmax()

3

In [37]:
# find min argumnet index
one = np.array([1,3,4,634,2])
one.argmin()

0

In [38]:
# element er value onujay index dekhay
one = np.array([1,3,4,634,2])
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [39]:
# minimum value er index ber korara jonno
one = np.array([1,3,4,634,2])
one.argmin()

0

In [40]:
# maximum value er index ber korar jonno
one = np.array([1,3,4,634,2])
one.argmax()

3

In [41]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [42]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [43]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [44]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [45]:
# marge all element
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [46]:
# reshape every element
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [47]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [48]:
# add to array from difference source
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [49]:
[324,34] + [34,546]

[324, 34, 34, 546]

In [50]:
# matrix multipication
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [51]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [52]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.sum()

29

In [53]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.max()

7

In [54]:
# find element an array
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [55]:
# count non zero element
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.count_nonzero(ar)

8

In [56]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [57]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar[1,2] = 0
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [58]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

112

In [59]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
np_ar.itemsize * np_ar.size

16

In [60]:
# tool list
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
np_ar.tolist()

[0, 4, 55, 2]