In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get dimention
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.ndim

2

In [5]:
# get shape
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.shape

(2, 3)

In [6]:
# get type
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.dtype

dtype('float64')

In [7]:
# get size
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype='int32')
b.size

6

In [8]:
# get total size
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.size * b.itemsize

48

In [9]:
# get bytes
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.nbytes

48

In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.itemsize

8

__Accessing/Changing specific elements, rows, columns, etc__

In [11]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# get shape
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x.shape

(2, 7)

In [13]:
# get specific element
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1,5]

13

In [15]:
# get a specific row
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# get specific colunms
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[:,2]

array([ 3, 10])

In [17]:
# getting a little fance [start-index:end-index:steps-size]
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[0, 1:6:2]

array([2, 4, 6])

In [18]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[:,2] = 5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [20]:
# 3d dimentional array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# get specific element (work outside in)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,1]

4

In [22]:
# get specific element (work outside in)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [23]:
# replace
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

__initilizing different types of array__

In [24]:
# all 0s matrix
np.zeros((2))

array([0., 0.])

In [25]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# all 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
# all 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [28]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((4,2,2),dtype='int32')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [30]:
# any other numbers
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [31]:
# any other number
np.full_like(a,4)

array([4, 4, 4])

In [32]:
# random decimal numbers
np.random.rand(4,2)

array([[0.74041736, 0.21758565],
       [0.95797815, 0.8541595 ],
       [0.98828021, 0.51708703],
       [0.85548077, 0.87809234]])

In [33]:
np.random.rand(4,2,3)

array([[[0.19043238, 0.59234371, 0.13834479],
        [0.44972778, 0.84116805, 0.79622729]],

       [[0.27867753, 0.90731146, 0.03859757],
        [0.82778097, 0.28925495, 0.19386509]],

       [[0.44744083, 0.06425232, 0.72556751],
        [0.9296635 , 0.03348727, 0.23166826]],

       [[0.50584894, 0.93361424, 0.68820843],
        [0.87990309, 0.36818641, 0.31147131]]])

In [34]:
# random integer values
np.random.randint(7)

0

In [35]:
np.random.randint(7,size=(3,3))

array([[0, 2, 2],
       [0, 4, 3],
       [1, 2, 3]])

In [36]:
np.random.randint(4,8,size=(3,3))

array([[5, 5, 7],
       [6, 7, 7],
       [5, 6, 7]])

In [37]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [40]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [42]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


__be careful when copying arrays!!__

In [44]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [45]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [46]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


__mathmematics__

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [49]:
a = np.array([1,2,3,4])
a - 2

array([-1,  0,  1,  2])

In [50]:
a = np.array([1,2,3,4])
a * 2

array([2, 4, 6, 8])

In [51]:
a = np.array([1,2,3,4])
a / 2

array([0.5, 1. , 1.5, 2. ])

In [52]:
b = np.array([1,0,1,0])
a = np.array([1,2,3,4])
a + b

array([2, 2, 4, 4])

In [53]:
a = np.array([1,2,3,4])
a ** 2

array([ 1,  4,  9, 16])

In [54]:
a = np.array([1,2,3,4])
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [55]:
a = np.array([1,2,3,4])
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

__linear alzebra__

In [56]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [57]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [58]:
# find the determinart
c = np.identity(3)
np.linalg.det(c)

1.0

In [59]:
# reference docs ()
# determinant
# trace
# singular vector Decomoposition
# eigenvalues
# matrix norm
# inverse
# etc

__statistics__

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [62]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats)

6

In [63]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats,axis=0)

array([1, 2, 3])

In [64]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats,axis=0)

array([4, 5, 6])

In [65]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats,axis=1)

array([1, 4])

In [66]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats,axis=1)

array([3, 6])

__Reognaizing Arrays__

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [68]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [69]:
# vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
# horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

__Mesellaneous__

Load Data from File

In [71]:
import numpy as np
np.genfromtxt('data.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   5.,
          6.,   7.,   0.,  11.,  12.,   3.,  19.],
       [  1.,  22.,  33.,  11., 999.,  12.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [72]:
import numpy as np
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   5.,
          6.,   7.,   0.,  11.,  12.,   3.,  19.],
       [  1.,  22.,  33.,  11., 999.,  12.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [73]:
import numpy as np
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   5,   6,   7,
          0,  11,  12,   3,  19],
       [  1,  22,  33,  11, 999,  12,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

__Boolean masking and Advanced Indexing__

In [74]:

import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [75]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [76]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [77]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
np.any(before>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [78]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
np.any(before>50,axis=1)

array([ True,  True,  True])

In [79]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
((before > 50) & (before < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [80]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
(~((before > 50) & (before < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])